variable "gcp_project" {}
variable "function_region" {}
variable "function_name" {}
variable "runtime" {}
variable "entry_point" {}
variable "source_root_dir" {}
variable "bucket_name" {}
variable "function_memory" {}
variable "function_max_instances" {}
variable "folder" {}
